apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  clusterIP: None
  ports:
  - name: webui
    port: 8081
  selector:
    app: flink
    component: jobmanager

---

apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
spec:
  clusterIP: None
  selector:
    app: flink
    component: taskmanager
